create table if not exists public.gm_products (
  id bigint generated by default as identity primary key,
  title text not null,
  price text not null default 'Consultar',
  description text default '',
  image_url text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.gm_motorcycles (
  id bigint generated by default as identity primary key,
  title text not null,
  year text default '',
  price text not null default 'Consultar',
  mileage text default '',
  description text default '',
  image_url text,
  image_urls jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.gm_gallery (
  id bigint generated by default as identity primary key,
  title text not null default 'Trabajo',
  category text not null default 'galeria',
  image_url text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.gm_reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  stars integer not null default 5 check (stars between 1 and 5),
  comment text not null,
  image_url text,
  approved boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists gm_products_order_idx on public.gm_products(active, sort_order, created_at desc);
create index if not exists gm_motorcycles_order_idx on public.gm_motorcycles(active, sort_order, created_at desc);
create index if not exists gm_gallery_order_idx on public.gm_gallery(active, sort_order, created_at desc);
create index if not exists gm_reviews_order_idx on public.gm_reviews(approved, sort_order, created_at desc);

alter table public.gm_products enable row level security;
alter table public.gm_motorcycles enable row level security;
alter table public.gm_gallery enable row level security;
alter table public.gm_reviews enable row level security;

drop policy if exists "Public read active products" on public.gm_products;
drop policy if exists "Public read active motorcycles" on public.gm_motorcycles;
drop policy if exists "Public read active gallery" on public.gm_gallery;
drop policy if exists "Public read approved reviews" on public.gm_reviews;

create policy "Public read active products"
  on public.gm_products for select
  using (active = true);

create policy "Public read active motorcycles"
  on public.gm_motorcycles for select
  using (active = true);

create policy "Public read active gallery"
  on public.gm_gallery for select
  using (active = true);

create policy "Public read approved reviews"
  on public.gm_reviews for select
  using (approved = true);
